export const NETWORK_TICK_RATE = 30;
export const NETWORK_TICK_INTERVAL = 1000 / NETWORK_TICK_RATE;

export const INTERPOLATION_BUFFER_MS = 50 + NETWORK_TICK_INTERVAL * 3;
export const MAX_EXTRAPOLATION_MS = NETWORK_TICK_INTERVAL * 2;

export const OFFSET_SMOOTHING = 0.1;
export const OFFSET_SNAP_THRESHOLD_MS = 250;

export const POSITION_SMOOTHING_SPEED = 18;
export const ROTATION_SMOOTHING_SPEED = 22;
