/**
 * Portal directory ("yellowpages") loader.
 *
 * Reads the flat `portals-index.json` manifest generated by the studio's
 * game-service whenever the scene is saved. Cached after first load.
 */

export interface PortalEntry {
  id: string;
  name: string;
  slug: string;
  image: string;
  position: { x: number; y: number; z: number };
  chunkKey: string;
}

/**
 * The studio image-upload control can store an upload descriptor object
 * (`{ path, image, ... }`) instead of a plain URL. Resolve either form (and a
 * stale manifest) down to a usable string so it never reaches an `<img src>`.
 */
function resolveImage(image: unknown): string {
  if (!image) return "";
  if (typeof image === "string") return image;
  if (typeof image === "object") {
    const o = image as Record<string, unknown>;
    return (o.path as string) || (o.image as string) || "";
  }
  return "";
}

let _cache: PortalEntry[] | null = null;

export async function loadPortals(baseUrl = ""): Promise<PortalEntry[]> {
  if (_cache) return _cache;
  try {
    const res = await fetch(`${baseUrl}/data/portals-index.json`);
    if (!res.ok) {
      _cache = [];
      return _cache;
    }
    const data = (await res.json()) as PortalEntry[];
    _cache = Array.isArray(data)
      ? data.map((p) => ({ ...p, image: resolveImage(p.image) }))
      : [];
  } catch {
    _cache = [];
  }
  return _cache;
}

/** Drop the cache so the next {@link loadPortals} re-fetches (e.g. after a save). */
export function invalidatePortals() {
  _cache = null;
}
